name: serb
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_screenutil: ^5.7.0

  dropdown_search: ^5.0.5

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  #unicorndial: "^1.1.5"
  fab_circular_menu: ^1.0.0
  #flutter_speed_dial: ^6.2.0
  #google_maps_place_picker: ^2.1.0-nullsafety.3
  google_maps_flutter: ^2.2.5
  shared_preferences: ^2.0.15
  #simple_animations: ^5.0.0+2
  #maps_launcher: ^2.0.1
  timeline_tile: ^2.0.0
  animate_do: ^3.0.2
  #qr_code_scanner: ^1.0.1
  image_picker: ^0.8.5+3
  #flutter_beep: ^1.0.0
  #soundpool: ^2.3.0
  #csc_picker: ^0.2.6
  otp_text_field: ^1.1.3
  #enhance_stepper: ^0.1.1
  easy_localization: ^3.0.1
  #country_list_pick: ^1.0.1+6
  toggle_switch: ^2.0.1
  #audioplayers: ^1.0.1
  #just_audio: ^0.9.29
  flutter_barcode_scanner: ^2.0.0
  #country_state_city_picker: ^1.2.8
  #country_icons: ^2.0.2
  #country_picker: ^2.0.19
  google_fonts: ^3.0.1
  #flutter_launcher_icons: ^0.10.0
  #flutter_boxicons: ^3.0.0
  url_launcher: ^6.1.6
  #motion_tab_bar_v2: ^0.2.6
  provider: ^5.0.0
  get: ^4.6.5
  #calendar_timeline: ^1.1.2
  awesome_dialog: ^3.1.0
  intl_phone_field: ^3.1.0
  carousel_slider: ^4.2.1
  web_socket_channel: ^2.4.0
  #firebase_core: ^2.3.0
  #firebase_auth: ^4.1.4
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  font_awesome_flutter: ^10.3.0
  #im_stepper: ^1.0.1+1
  #countries_utils: ^1.0.1
  folding_cell: ^1.0.0
  #slide_popup_dialog_null_safety: ^1.0.0
  conditional_builder_null_safety: ^0.0.6
  #material_dialogs: ^1.1.4
  #flutter_hooks: ^0.18.5+1
  geolocator: ^7.0.1
  geocoding: ^2.0.5
  easy_stepper: ^0.3.1
  #multi_select_item: ^1.0.3
  #popup_menu: ^1.0.5
  flutter_awesome_alert_box: ^2.1.1
  numberpicker: ^2.0.0
  path_provider: ^2.0.12
  floating_action_bubble: ^1.1.4
  dropdown_button2: ^1.9.2


  #animated_bottom_navigation_bar: ^1.1.0+1
  #flutter_localized_locales: ^2.0.4
  latlng: ^0.2.0
  flutter_map: ^3.1.0
  pinput: ^2.2.31

  dotted_border: ^2.0.0+3
  #card_scanner: ^0.2.2
  pay: ^1.1.0
  flutter_credit_card: ^2.0.0
  flutter_contacts: ^1.1.6
  file_picker:
  awesome_bottom_bar: ^1.2.2
  #fluttercontactpicker: ^4.7.0
  permission_handler: ^6.0.1+1
  contacts_service: ^0.6.3
  dio: ^5.0.0
  timer_builder: ^2.0.0
  camera: ^0.9.4+5
  #flutter_polyline_points: ^1.0.0
  http: ^0.13.5
  #libphonenumber: ^2.0.2
  fluttertoast: ^8.2.1
  smooth_page_indicator: ^1.0.1
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^7.4.0
  equatable: ^2.0.5
  #test: ^1.22.0
  #mobile_scanner: ^3.0.0

  local_auth: ^2.1.6
  #flutter_secure_storage: ^8.0.0



  #flutter_chat_types: ^3.6.0
  #mime: ^1.0.2
  #open_filex: ^4.2.2
  #uuid: ^3.0.6
  #chatview: ^1.2.1

  #barcode_scan2: ^4.2.4
  scan: ^1.6.0
  #intl_phone_number_input: ^0.7.3+1
  #flutter_pw_validator:

  screenshot: ^2.1.0

  image_gallery_saver: ^1.6.9
  multiple_images_picker: ^1.0.1
  #flutter_image_compress: ^1.1.3
  flutter_native_image: ^0.0.6+1
  pull_to_refresh: ^2.0.0
  awesome_snackbar_content: ^0.1.3
  path: ^1.8.2
  chatview: ^1.0.1
  #flutter_animated_button: ^2.0.3
  #flutter_background_service: ^3.0.1
  #flutter_local_notifications: ^14.1.1
  circular_menu:

  flutter_speed_dial: ^3.0.5
  maps_launcher: ^2.2.0


dependency_overrides:
  device_info_plus: ^9.0.2
  audio_waveforms: 1.0.1
  qr_flutter: ^4.0.0
  intl: ^0.18.0
  #connectivity: ^3.0.6
  connectivity_plus: ^3.0.0
  #phone_number: ^2.0.1
  #meta: ^1.9.1
  #pdf: ^3.10.1
  share_plus:
  flutter_launcher_icons: ^0.13.1
  #image: ^4.0.0
  #device_preview: ^1.1.0
  provider: ^5.0.0
  #flutter_native_image: ^0.0.6+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/serb_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

